project_id = "uzfvianjqrdimuxkaqvf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbuckets]
enabled = true
port = 54324

[edge_runtime]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[functions.google-drive-auth]
verify_jwt = false